---
title: "EcoEnto"
author: "Marcela Morassi"
date: "11/30/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

SetUp
```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(vegan)
library(RColorBrewer)
library(patchwork)
theme_set(theme_classic()) # Set the theme


setwd("C:/Users/Marcela Morassi/Documents/Github/EcoEnto")

data <- read.csv("data.csv", na.strings=c("","NA"))
og_data <- read.csv("og_data.csv", na.strings=c("","NA"))

```


Moth data manipulation
```{r}
#filtering only order lep w og data
moth_data <- og_data %>% 
  filter(order == "Lepidoptera") %>% 
  select(family, genus, species, eventDate, day, month, year, identifiedBy, recordedBy, institutionCode) %>% 
  filter(!family %in% c("Nymphalidae","Papilionidae","Pieridae","Hesperiidae")) %>% 
  filter(!is.na(recordedBy)) %>% 
  mutate(year=as.character(year))

#adding seasons column
moth_data<- moth_data %>% 
  mutate(season = case_when(
    month %in% 9:11 ~ "fall",
    month %in% c(1, 2, 12) ~ "winter",
    month %in% 6:8 ~ "summer",
    month %in% 3:5 ~ "spring"
    )) %>% 
  mutate(season = factor(season, levels = c("spring", "summer", "fall", "winter"))) %>% 
  filter(year>1990&year<2005)

#count of moth obs per year
moth_year_count = moth_data %>% 
  group_by(year) %>% # Group by what you want
  summarise(count = n()) %>% 
  mutate(perc = count / sum(count)) %>% 
  filter(!is.na(year))
#species count by season
moth_species_count <- moth_data %>% 
  filter(year>1990&year<2005) %>% 
  group_by(species, season) %>% # Group by what you want
  summarise(count = n()) %>% 
  filter(!is.na(season)) 
#genus count by season
moth_genus_count = moth_data %>% 
  group_by(genus, season) %>% 
  summarise(count=n()) %>% 
  filter(!is.na(season)) 
#fam count by genus
moth_fam_count = moth_data %>% 
  group_by(family, season) %>% 
  summarise(count=n()) %>% 
  filter(!is.na(season))
#fam by season+yr
fam_yr_count = moth_data %>% 
  group_by(family, year, season) %>% # Group by what you want
  summarise(count = n()) %>% 
  group_by(year) %>% 
  mutate(    perc = count / sum(count))%>% 
  filter(!is.na(season))
#species by season+yr
species_yr_count = moth_data %>% 
  group_by(species, year, season) %>% 
  summarise(count=n()) %>% 
  filter(!is.na(season)) %>% 
  filter(!is.na(species))

```

moth data visualization
```{r}
#bar chart of lep fam og data
ggplot(moth_fam_count, aes(x = "", y = perc, fill = family)) +
  geom_bar(width = 1, stat = "identity", color = "white", position = "dodge")

#bar charts of lep fam faceted
ggplot(moth_fam_count, aes(x = "", y = perc, fill = family)) +
  geom_bar(width = 1, stat = "identity", color = "white", position = "dodge")+
  facet_wrap(facets = vars(year))

#moth count by year
ggplot(moth_year_count, aes(x = year, y = count, fill = year)) +
  geom_bar(stat="identity",position = "dodge")

###
#shannon diversity avg for each season
##jacaard index for each pairwise (spr-su,spri-fall, etc)
#

```

moth shannon index
```{r}

##Shannon's Diversity function
shannon_diversity = function(species, count) {
  # species: vector of species names; 
  # count: how many of each species are present
  
  # Create p, a vector of relative frequencies
  p = tibble(species, count) %>% 
    # Merge duplicate species 
    group_by(species) %>% 
    summarize(count = sum(count)) %>% 
    ungroup() %>% 
    # Remove zeroes
    filter(count > 0) %>% 
    # Convert to frequencies
    mutate(p = count / sum(count)) %>% 
    # Extract column p
    pull(p) 
  if(length(p) < 2) return(0) # one or 0 species has an H of 0
  exp( -sum(p * log(p)) ) # exponential of shannon index
}

#shannon diversity data frame
moth_shannon <- moth_species_count %>% 
  group_by(season) %>% 
  summarize(shannon = shannon_diversity(species, count),
            richness = n()) 
#plotting shannon diversity by season
shannon1 <- ggplot(moth_shannon, aes(x=season, y = shannon)) + 
  geom_point()+
  ylab("true Shannon diversity")+
  scale_x_discrete(limits = c("spring", "summer", "fall", "winter"))
ggsave("shannon_species.png")

#shannn diversity by seasonANDyear df
moth_shannon2 <- species_yr_count %>%
  group_by(season,year) %>% 
  summarize(shannon=shannon_diversity(species,count),
            richness=n()) %>% 
  mutate(avg_shannon = mean(shannon)) 
#plotted
shannon2<-ggplot(moth_shannon2, aes(x=season, y=shannon, color=year))+
  geom_point()+
  ylab("true Shannon diversity")+
  scale_x_discrete(limits = c("spring", "summer", "fall", "winter"))
ggsave("shannon_fig2.png")

shannon1 + shannon2
ggsave("shannon_combined.png", width = 14, height = 7)
```


Rank Abundance Curves - Species
```{r}

plot_rank_abundance = function(data_long2, right_margin = 2.8) {
  # Make the rank abundance plot
  # The right_margin argument is used to make sure that 
  # the angled axis labels don't go of the page
  # make it larger or smaller to suit your tastes
  ggplot(data_long2, aes(x = reorder(species,(-count)), y = count)) +
    geom_line(group = 1) + # Create a descending line
    scale_y_log10() + # puts y axis on log scale
    xlab("Species") + ylab("N")+
    theme(axis.text.x =  # cleans up appearance of x axis labels
            element_text(angle = -25, hjust = 0.05, # angled, justified text
                         vjust = 1, face = "italic"), # also in italics
          # makes sure that the axis labels don't go off the page
          plot.margin = unit(c(0,right_margin,0,0)+.1, "cm"))
  # Be sure sure that Species has been coded as a factor, in decreasing order of N!
}

#species rank abundance curve
#spring
RAC_species_spring  <- moth_species_count %>% 
  filter(season=="spring") %>% 
  filter(!is.na(species)) %>% 
  plot_rank_abundance()
ggsave("RAC_species_spring.png")
#summer
RAC_species_summer <- moth_species_count %>% 
  filter(season=="summer") %>% 
  filter(!is.na(species)) %>% 
  plot_rank_abundance()
ggsave("RAC_species_summer.png")
#fall
RAC_species_fall <- moth_species_count %>% 
  filter(season=="fall") %>% 
  filter(!is.na(species)) %>% 
  plot_rank_abundance()
ggsave("RAC_species_fall.png")
#fall
RAC_species_winter <- moth_species_count %>% 
  filter(season=="winter") %>% 
  filter(!is.na(species)) %>% 
  plot_rank_abundance()
ggsave("RAC_species_winter.png")
#overall
RAC_overall <- moth_data %>% 
  group_by(species) %>% 
  summarise(count=n()) %>% 
  ungroup() %>% 
  filter(!is.na(species)) %>% 
  filter(count>1) %>% 
  plot_rank_abundance()

RAC_species_spring+RAC_species_summer+RAC_species_fall+RAC_species_winter+RAC_overall+
  plot_layout(nrow = 5, byrow = FALSE)+
  plot_annotation(tag_levels=list(c("spring","summer","fall","winter","overall")))
ggsave("RAC_species.png", width = 20, height = 10)

```

Rank Abundance Curves - genus
```{r}
plot_rank_abundance_genus = function(data_long2, right_margin = 2.8) {
  # Make the rank abundance plot
  # The right_margin argument is used to make sure that 
  # the angled axis labels don't go of the page
  # make it larger or smaller to suit your tastes
  ggplot(data_long2, aes(x = reorder(genus,(-count)), y = count)) +
    geom_line(group = 1) + # Create a descending line
    scale_y_log10() + # puts y axis on log scale
    xlab("Genus") + ylab("N")+
    theme(axis.text.x =  # cleans up appearance of x axis labels
            element_text(angle = -25, hjust = 0.05, # angled, justified text
                         vjust = 1, face = "italic"), # also in italics
          # makes sure that the axis labels don't go off the page
          plot.margin = unit(c(0,right_margin,0,0)+.1, "cm"))
  # Be sure sure that Species has been coded as a factor, in decreasing order of N!
}

#species rank abundance curve
#spring  <- moth_species_count %>% 
g_sp <- moth_genus_count %>% 
  filter(season=="spring") %>% 
  filter(!is.na(genus)) %>% 
  plot_rank_abundance_genus()
#summer
g_su <- moth_genus_count %>% 
  filter(season=="summer") %>% 
  filter(!is.na(genus)) %>% 
  plot_rank_abundance_genus()
#fall
g_fa <- moth_genus_count %>% 
  filter(season=="fall") %>% 
  filter(!is.na(genus)) %>% 
  plot_rank_abundance_genus()
#winter
g_wi <- moth_genus_count %>% 
  filter(season=="winter") %>% 
  filter(!is.na(genus)) %>% 
  plot_rank_abundance_genus()
#overall
g_ov <- moth_data %>% 
  group_by(genus) %>% 
  summarise(count=n()) %>% 
  filter(!is.na(genus)) %>% 
  filter(count>1) %>% 
  plot_rank_abundance_genus()

g_sp+g_su+g_fa+g_wi+g_ov+
  plot_layout(nrow = 5, byrow = FALSE)+
  plot_annotation(tag_levels=list(c("spring","summer","fall","winter")))
ggsave("RAC_genus.png", height = 10, width = 20)
```

Rank Abundance Curves - family
```{r}
plot_rank_abundance_fam = function(data_long2, right_margin = 2.8) {
  # Make the rank abundance plot
  # The right_margin argument is used to make sure that 
  # the angled axis labels don't go of the page
  # make it larger or smaller to suit your tastes
  ggplot(data_long2, aes(x = reorder(family,(-count)), y = count)) +
    geom_line(group = 1) + # Create a descending line
    scale_y_log10() + # puts y axis on log scale
    xlab("Family") + ylab("N")+
    theme(axis.text.x =  # cleans up appearance of x axis labels
            element_text(angle = -25, hjust = 0.05, # angled, justified text
                         vjust = 1, face = "italic"), # also in italics
          # makes sure that the axis labels don't go off the page
          plot.margin = unit(c(0,right_margin,0,0)+.1, "cm"))
  # Be sure sure that Species has been coded as a factor, in decreasing order of N!
}

#species rank abundance curve
#spring  <- moth_species_count %>% 
f_sp <- moth_fam_count %>%
  filter(season=="spring") %>% 
  filter(!is.na(family)) %>% 
  plot_rank_abundance_fam()
#summer
f_su <- moth_fam_count %>% 
  filter(season=="summer") %>% 
  filter(!is.na(family)) %>% 
  plot_rank_abundance_fam()
#fall
f_fa <- moth_fam_count %>% 
  filter(season=="fall") %>% 
  filter(!is.na(family)) %>% 
  plot_rank_abundance_fam()
#winter
f_wi <- moth_fam_count %>% 
  filter(season=="winter") %>% 
  filter(!is.na(family)) %>% 
  plot_rank_abundance_fam()
#overall
f_ov <- moth_data %>% 
  group_by(family) %>% 
  summarise(count=n()) %>% 
  filter(!is.na(family)) %>% 
  plot_rank_abundance_fam()

f_sp+f_su+f_fa+f_wi+f_ov+
  plot_layout(nrow = 5, byrow = FALSE)+
  plot_annotation(tag_levels=list(c("spring","summer","fall","winter")))
ggsave("RAC_family.png")
```


Species Abundance analyses
```{r}
#most abundant species by season
moth_species_count %>% 
  group_by(season) %>% 
  slice_max(order_by=count, n=5) 
#most abundant species overall
moth_data %>% 
  group_by(species) %>% 
  summarise(count=n()) %>% 
  ungroup() %>% 
  slice_max(order_by = count, n=10)
#most abundant fam by season
moth_fam_count %>% 
  ungroup() %>% 
  select(family, season, count) %>% 
  group_by(season) %>% 
  slice_max(order_by = count, n=5)
#most abundant genus by season
moth_genus_count %>% 
  group_by(season) %>% 
  slice_max(order_by = count, n=5)

```


Jaccard similarity
```{r}
jaccard_similarity = function(com_1, com_2) {
  # com_1 and com_2 are the arguments of the function, 
  # they should be the names in different communities
  
  # Create local variables for the intersection and union;
  common_spp = intersect(com_1, com_2) 
  total_spp = union(com_1, com_2) 
  # these variables are created while the function runs & destroyed when it ends
  # The last value of the function is its output (a.k.a., return value)
  length(common_spp) / length(total_spp) # return this
}
###SPECIES
com_spring = moth_species_count %>% 
  # Subset the data to get the "community" you want
  filter(season == "spring") %>% 
  # Get the list of species as a vector
  pull(species) %>% unique()

com_summer = moth_species_count %>% 
  filter(season == "summer") %>% 
  pull(species) %>% unique()

com_fall = moth_species_count %>% 
  filter(season == "fall") %>% 
  pull(species) %>% unique()

com_winter = moth_species_count %>% 
  filter(season == "winter") %>% 
  pull(species) %>% unique()

jaccard_similarity(com_spring, com_summer)
# 0.1666667
jaccard_similarity(com_spring,com_fall)
#0.1590909
jaccard_similarity(com_spring,com_winter)
#0.05405405
jaccard_similarity(com_summer, com_fall)
#0.1176471
jaccard_similarity(com_summer, com_winter)
#0
jaccard_similarity(com_fall, com_winter)
#0.02325581

###GENUS
com_spring2 = moth_genus_count %>% 
  filter(season == "spring") %>% 
  pull(genus) %>% unique()

com_summer2 = moth_genus_count %>% 
  filter(season == "summer") %>% 
  pull(genus) %>% unique()

com_fall2 = moth_genus_count %>% 
  filter(season == "fall") %>% 
  pull(genus) %>% unique()

com_winter2 = moth_genus_count %>% 
  filter(season == "winter") %>% 
  pull(genus) %>% unique()

jaccard_similarity(com_spring2, com_summer2)
#0.2142857
jaccard_similarity(com_spring2,com_fall2)
# 0.21875
jaccard_similarity(com_spring2,com_winter2)
#0.09615385
jaccard_similarity(com_summer2, com_fall2)
#0.1627907
jaccard_similarity(com_summer2, com_winter2)
#0.03571429
jaccard_similarity(com_fall2, com_winter2)
#0.08333333

###FAMILY
com_spring3 = moth_fam_count %>% 
  filter(season == "spring") %>% 
  pull(family) %>% unique()

com_summer3 = moth_fam_count %>% 
  filter(season == "summer") %>% 
  pull(family) %>% unique()

com_fall3 = moth_fam_count %>% 
  filter(season == "fall") %>% 
  pull(family) %>% unique()

com_winter3 = moth_fam_count %>% 
  filter(season == "winter") %>% 
  pull(family) %>% unique()

jaccard_similarity(com_spring3, com_summer3)
# 0.5263158
jaccard_similarity(com_spring3,com_fall3)
#0.45
jaccard_similarity(com_spring3,com_winter3)
#0.2631579
jaccard_similarity(com_summer3, com_fall3)
# 0.8333333
jaccard_similarity(com_summer3, com_winter3)
#0.4166667
jaccard_similarity(com_fall3, com_winter3)
#0.3076923
```


